In [1]:
import openai

from typing import List, Iterator
import pandas as pd
import numpy as np
import os
import pickle
from ast import literal_eval

# Redis client library for Python
import redis
from redis.commands.search.indexDefinition import (
    IndexDefinition,
    IndexType
)
from redis.commands.search.query import Query
from redis.commands.search.field import (
    TextField,
    VectorField
)

# I've set this to our new embeddings model, this can be changed to the embedding model of your choice
EMBEDDING_MODEL = "text-embedding-3-small"

# Ignore unclosed SSL socket warnings - optional in case you get these errors
import warnings

warnings.filterwarnings(action="ignore", message="unclosed", category=ResourceWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)

#### Load Data

In [2]:
transcript_df = pd.read_csv('data/embeddings.csv')

In [3]:
transcript_df.head()

,vector_id,id,video_key,chunk_key,content_vector,title_vector
0,0,0,4b6bwcWK6GE,4b6bwcWK6GE_chunk_0,"[0.007409781217575073, -0.004786759149283171, ...","[-0.027406472712755203, -0.012386651709675789,..."
1,1,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_0,"[0.0029184420127421618, -0.010121479630470276,...","[-0.02722085453569889, 0.0020761173218488693, ..."
2,2,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_1,"[0.0036486308090388775, -0.019859155640006065,...","[-0.02722085453569889, 0.0020761173218488693, ..."
3,3,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_2,"[-0.008065965957939625, -0.04014651104807854, ...","[-0.02722085453569889, 0.0020761173218488693, ..."
4,4,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_3,"[0.02524896338582039, 0.006082533393055201, -0...","[-0.02722085453569889, 0.0020761173218488693, ..."

In [4]:
# Load title dictionary from pickle file
with open('data/title_dict.pkl', 'rb') as f:
    title_dict = pickle.load(f)

title_df = pd.DataFrame(title_dict.items(), columns=['video_key', 'title'])
title_df.head()

     video_key                                              title
0  4b6bwcWK6GE                Welcome to the Huberman Lab Podcast
1  H-XfCl-HpRM                     How Your Brain Works & Changes
2  nm1TxQj9IsQ       Master Your Sleep & Be More Alert When Awake
3  nwSkFq4tyC0  Using Science to Optimize Sleep, Learning & Me...
4  NAATB55oxeQ  How to Defeat Jet Lag, Shift Work & Sleeplessness

In [5]:
# Load title dictionary from pickle file
with open('data/chunk_dict.pkl', 'rb') as f:
    chunk_dict = pickle.load(f)

chunk_df = pd.DataFrame(chunk_dict.items(), columns=['chunk_key', 'text'])
chunk_df.head()

             chunk_key                                               text
0  4b6bwcWK6GE_chunk_0  - Welcome to the Huberman Lab Podcast\nwhere w...
1  H-XfCl-HpRM_chunk_0  - Welcome to the Huberman Lab Podcast\nwhere w...
2  H-XfCl-HpRM_chunk_1  which is more a measure\nof your biological ag...
3  H-XfCl-HpRM_chunk_2  If I play the keys on a\npiano in a particular...
4  H-XfCl-HpRM_chunk_3  We come into the world and\nour brain has a ki...

In [6]:
# Join transcript_df with title_df on video_id to add titles
transcript_df = transcript_df.merge(title_df, on='video_key', how='left')
transcript_df = transcript_df.merge(chunk_df, on='chunk_key', how='left')
transcript_df.head()

,vector_id,id,video_key,chunk_key,content_vector,title_vector,title,text
0,0,0,4b6bwcWK6GE,4b6bwcWK6GE_chunk_0,"[0.007409781217575073, -0.004786759149283171, ...","[-0.027406472712755203, -0.012386651709675789,...",Welcome to the Huberman Lab Podcast,- Welcome to the Huberman Lab Podcast\nwhere w...
1,1,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_0,"[0.0029184420127421618, -0.010121479630470276,...","[-0.02722085453569889, 0.0020761173218488693, ...",How Your Brain Works & Changes,- Welcome to the Huberman Lab Podcast\nwhere w...
2,2,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_1,"[0.0036486308090388775, -0.019859155640006065,...","[-0.02722085453569889, 0.0020761173218488693, ...",How Your Brain Works & Changes,which is more a measure\nof your biological ag...
3,3,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_2,"[-0.008065965957939625, -0.04014651104807854, ...","[-0.02722085453569889, 0.0020761173218488693, ...",How Your Brain Works & Changes,If I play the keys on a\npiano in a particular...
4,4,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_3,"[0.02524896338582039, 0.006082533393055201, -0...","[-0.02722085453569889, 0.0020761173218488693, ...",How Your Brain Works & Changes,We come into the world and\nour brain has a ki...

In [7]:
# Read vectors from strings back into a list
transcript_df['title_vector'] = transcript_df.title_vector.apply(literal_eval)
transcript_df['content_vector'] = transcript_df.content_vector.apply(literal_eval)

# Set vector_id to be a string
transcript_df['video_key'] = transcript_df['video_key'].apply(str)

In [8]:
transcript_df

,vector_id,id,video_key,chunk_key,content_vector,title_vector,title,text
0,0,0,4b6bwcWK6GE,4b6bwcWK6GE_chunk_0,"[0.007409781217575073, -0.004786759149283171, ...","[-0.027406472712755203, -0.012386651709675789,...",Welcome to the Huberman Lab Podcast,- Welcome to the Huberman Lab Podcast\nwhere w...
1,1,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_0,"[0.0029184420127421618, -0.010121479630470276,...","[-0.02722085453569889, 0.0020761173218488693, ...",How Your Brain Works & Changes,- Welcome to the Huberman Lab Podcast\nwhere w...
2,2,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_1,"[0.0036486308090388775, -0.019859155640006065,...","[-0.02722085453569889, 0.0020761173218488693, ...",How Your Brain Works & Changes,which is more a measure\nof your biological ag...
3,3,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_2,"[-0.008065965957939625, -0.04014651104807854, ...","[-0.02722085453569889, 0.0020761173218488693, ...",How Your Brain Works & Changes,If I play the keys on a\npiano in a particular...
4,4,1,H-XfCl-HpRM,H-XfCl-HpRM_chunk_3,"[0.02524896338582039, 0.006082533393055201, -0...","[-0.02722085453569889, 0.0020761173218488693, ...",How Your Brain Works & Changes,We come into the world and\nour brain has a ki...
...,...,...,...,...,...,...,...,...
7462,7462,287,9vQZT2igXN4,9vQZT2igXN4_chunk_35,"[0.03465878590941429, -0.006087542045861483, -...","[-0.03055098094046116, 0.002287362702190876, 0...",How Different Diets Impact Your Health | Dr. C...,the cannabis research community. I\ninvited th...
7463,7463,287,9vQZT2igXN4,9vQZT2igXN4_chunk_36,"[0.018512507900595665, -0.003153152298182249, ...","[-0.03055098094046116, 0.002287362702190876, 0...",How Different Diets Impact Your Health | Dr. C...,that they hadn't eaten any fermented\nfood har...
7464,7464,287,9vQZT2igXN4,9vQZT2igXN4_chunk_37,"[0.020002253353595734, -0.014687786810100079, ...","[-0.03055098094046116, 0.002287362702190876, 0...",How Different Diets Impact Your Health | Dr. C...,"reactive protein, not interlucan 6, not\ntrime..."
7465,7465,287,9vQZT2igXN4,9vQZT2igXN4_chunk_38,"[0.034738194197416306, -0.025965649634599686, ...","[-0.03055098094046116, 0.002287362702190876, 0...",How Different Diets Impact Your Health | Dr. C...,of other things but I I see significant\nimpro...
7466,7466,287,9vQZT2igXN4,9vQZT2igXN4_chunk_39,"[0.006070644594728947, 0.011910713277757168, -...","[-0.03055098094046116, 0.002287362702190876, 0...",How Different Diets Impact Your Health | Dr. C...,are many of them that don't change.\nThere are...

In [9]:
transcript_df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7467 entries, 0 to 7466
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   vector_id       7467 non-null   int64
 1   id              7467 non-null   int64
 2   video_key       7467 non-null   object
 3   chunk_key       7467 non-null   object
 4   content_vector  7467 non-null   object
 5   title_vector    7467 non-null   object
 6   title           7467 non-null   object
 7   text            7467 non-null   object
dtypes: int64(2), object(6)
memory usage: 466.8+ KB

### Redis

#### Setup

In [10]:
REDIS_HOST =  "localhost"
REDIS_PORT = 6379
REDIS_PASSWORD = "" # default for passwordless Redis

# Connect to Redis
redis_client = redis.Redis(
    host=REDIS_HOST,
    port=REDIS_PORT,
    password=REDIS_PASSWORD
)
redis_client.ping()

True

#### Creating a Search Index

The below cells will show how to specify and create a search index in Redis. We will

1. Set some constants for defining our index like the distance metric and the index name
2. Define the index schema with RediSearch fields
3. Create the index

In [11]:
# Constants
VECTOR_DIM = len(transcript_df['title_vector'][0]) # length of the vectors
VECTOR_NUMBER = len(transcript_df)                 # initial number of vectors
INDEX_NAME = "embeddings-index"                    # name of the search index
PREFIX = "doc"                                     # prefix for the document keys
DISTANCE_METRIC = "COSINE"                         # distance metric for the vectors (ex. COSINE, IP, L2)

In [12]:
# Define RediSearch fields for each of the columns in the dataset
title = TextField(name="title")
text = TextField(name="text")
video_key = TextField(name="video_key")
chunk_key = TextField(name="chunk_key")
# url = TextField(name="url")

title_embedding = VectorField("title_vector",
    "FLAT", {
        "TYPE": "FLOAT32",
        "DIM": VECTOR_DIM,
        "DISTANCE_METRIC": DISTANCE_METRIC,
        "INITIAL_CAP": VECTOR_NUMBER,
    }
)
text_embedding = VectorField("content_vector",
    "FLAT", {
        "TYPE": "FLOAT32",
        "DIM": VECTOR_DIM,
        "DISTANCE_METRIC": DISTANCE_METRIC,
        "INITIAL_CAP": VECTOR_NUMBER,
    }
)
fields = [title, text, video_key, chunk_key, title_embedding, text_embedding]

In [13]:
# Check if index exists
try:
    redis_client.ft(INDEX_NAME).info()
    print("Index already exists")
except:
    # Create RediSearch Index
    redis_client.ft(INDEX_NAME).create_index(
        fields = fields,
        definition = IndexDefinition(prefix=[PREFIX], index_type=IndexType.HASH)
    )

#### Load Documents into Index

In [14]:
def index_documents(client: redis.Redis, prefix: str, documents: pd.DataFrame):
    records = documents.to_dict("records")
    for doc in records:
        key = f"{prefix}:{str(doc['id'])}"

        # create byte vectors for title and content
        title_embedding = np.array(doc["title_vector"], dtype=np.float32).tobytes()
        content_embedding = np.array(doc["content_vector"], dtype=np.float32).tobytes()

        # replace list of floats with byte vectors
        doc["title_vector"] = title_embedding
        doc["content_vector"] = content_embedding

        client.hset(key, mapping = doc)

In [15]:
index_documents(redis_client, PREFIX, transcript_df)
print(f"Loaded {redis_client.info()['db0']['keys']} documents in Redis search index with name: {INDEX_NAME}")

Loaded 261 documents in Redis search index with name: embeddings-index

#### Running Search Queries

In [16]:
def search_redis(
    openai_client: openai.OpenAI,
    redis_client: redis.Redis,
    user_query: str,
    index_name: str = "embeddings-index",
    vector_field: str = "title_vector",
    return_fields: list = ["title", "text", "chunk_key", "vector_score"],
    hybrid_fields = "*",
    k: int = 10,
) -> List[dict]:

    # Creates embedding vector from user query
    embedded_query = openai_client.embeddings.create(input=user_query,
                                            model=EMBEDDING_MODEL,
                                            ).data[0].embedding

    # Prepare the Query
    base_query = f'{hybrid_fields}=>[KNN {k} @{vector_field} $vector AS vector_score]'
    query = (
        Query(base_query)
         .return_fields(*return_fields)
         .sort_by("vector_score")
         .paging(0, k)
         .dialect(2)
    )
    params_dict = {"vector": np.array(embedded_query).astype(dtype=np.float32).tobytes()}

    # perform vector search
    results = redis_client.ft(index_name).search(query, params_dict)
    for i, article in enumerate(results.docs):
        score = 1 - float(article.vector_score)
        print(f"{i}. {article.title}\n(Score: {round(score ,3) })")
    return results.docs

In [17]:
# For using OpenAI to generate query embedding
from dotenv import load_dotenv
load_dotenv()
open_api_key = os.getenv("OPENAI_API_KEY")
openai_client = openai.OpenAI(api_key=open_api_key)

In [18]:
results = search_redis(
    openai_client, 
    redis_client, 
    'dopamine in the brain', 
    k=10
)

0. Time Perception & Entrainment by Dopamine, Serotonin & Hormones
(Score: 0.428)
1. Dr. Robert Malenka: How Your Brainâs Reward Circuits Drive Your Choices
(Score: 0.403)
2. Leverage Dopamine to Overcome Procrastination & Optimize Effort | Huberman Lab Podcast
(Score: 0.377)
3. How Relationships Shape Your Brain | Dr. Allan Schore
(Score: 0.346)
4. Control Pain & Heal Faster With Your Brain | Huberman Lab Essentials
(Score: 0.342)
5. How Your Brain Works & Changes
(Score: 0.334)
6. Using Play to Rewire & Improve Your Brain
(Score: 0.332)
7. Essentials: How Your Brain Works & Changes
(Score: 0.332)
8. Dr. Mark D'Esposito: How to Optimize Cognitive Function & Brain Health
(Score: 0.329)
9. Optimize & Control Your Brain Chemistry to Improve Health & Performance | Huberman Lab Podcast #80
(Score: 0.314)

In [19]:
results[0].text

"It's simply Huberman Lab on YouTube.\nAnd there you can also\nleave us suggestions\nfor future guests and topics\nand questions about the podcast episodes\nin the comments section on YouTube.\nIn addition, please\nsubscribe to our podcast\non Apple and/or Spotify, and on Apple,\nyou have the opportunity to leave us\nup to a five star review.\nYou can also follow us on Instagram.\nOn Instagram I do short\nneuroscience tutorials\nand tools and protocols.\nI cover recent papers,\nmany of which are not\nincluded on the podcast.\nWe also have a Patreon. It's\npatreon.com/andrewhuberman.\nAnd there you can support the podcast\nat any level that you like.\nNot so much today but on\nmany previous episodes\nof the Huberman Lab Podcast,\nwe discuss supplements,\nand while supplements aren't\nnecessary for everybody,\nmany people derive great\nbenefit from supplements\nfor sleep, for focus, and so forth.\nOne issue with supplements,\nhowever, is that what's listed\non the bottle of various supplements\nisn't always what's included in the bottle\nand the quality of ingredients\nvaries tremendously\nacross different supplement manufacturers.\nFor that reason, we've\npartnered with Thorne,\nthat's T-H-O-R-N-E,\nbecause Thorne supplements\nhave the highest levels\nof stringency of any\nsupplement company out there\nthat we are aware of.\nThey work with all the major sports teams.\nThey work with the Mayo Clinic.\nAnd so we're delighted that\nwe partnered with them.\nIf you'd like to see the\nsupplements that I take,\nyou can go to Thorne,\nthat's T-H-O-R-N-E, .com\nslash the letter U slash Huberman\nto see the supplements that I take\nand you can get 20% off\nany of those supplements.\nIf you enter the Thorne\nsite through that portal,\nyou can also get 20% off\nany of the supplements\nthat Thorne makes.\nThank you for your time\nand attention today,\nand last but certainly not least,\nthank you for your interest in science.\n[bright guitar music]"

In [20]:
results = search_redis(
    openai_client, 
    redis_client, 
    'Sleep and Exercise', 
    vector_field='content_vector', 
    k=10
)

0. How to Defeat Jet Lag, Shift Work & Sleeplessness | Huberman Lab Essentials
(Score: 0.494)
1. Dr. Matt Walker: The Biology of Sleep & Your Unique Sleep Needs | Huberman Lab Guest Series
(Score: 0.432)
2. Optimize Your Learning & Creativity With Science-Based Tools | Huberman Lab Essentials
(Score: 0.426)
3. Dr. Gina Poe: Use Sleep to Enhance Learning, Memory & Emotional State | Huberman Lab Podcast
(Score: 0.416)
4. How to Heal From Post-Traumatic Stress Disorder (PTSD) | Dr. Victor CarriÃ³n
(Score: 0.41)
5. Dr. Matt Walker: Improve Sleep to Boost Mood & Emotional Regulation | Huberman Lab Guest Series
(Score: 0.409)
6. Create Your Ideal Future Using Science-Based Protocols | Ari Wallach
(Score: 0.407)
7. Master Your Sleep & Be More Alert When Awake
(Score: 0.406)
8. AMA #14: 2023 Philanthropy, Evening Routine, Light Therapy, Health Metrics & More
(Score: 0.403)
9. Lose Fat With Science-Based Tools | Huberman Lab Essentials
(Score: 0.402)

#### Hybrid Queries with Redis

In [21]:
def create_hybrid_field(field_name: str, value: str) -> str:
    return f'@{field_name}:"{value}"'

In [22]:
# search the content vector for articles about famous battles in Scottish history and only include results with Scottish in the title
results = search_redis(openai_client,
                       redis_client,
                       "Sleep and Exercise",
                       vector_field="title_vector",
                       k=5,
                       hybrid_fields=create_hybrid_field("title", "Huberman")
                       )

0. Using Science to Optimize Sleep, Learning & Metabolism | Huberman Lab Essentials
(Score: 0.521)
1. How to Defeat Jet Lag, Shift Work & Sleeplessness | Huberman Lab Essentials
(Score: 0.488)
2. Dr. Matt Walker: Protocols to Improve Your Sleep | Huberman Lab Guest Series
(Score: 0.47)
3. Sleep Toolkit: Tools for Optimizing Sleep & Sleep-Wake Timing | Huberman Lab Podcast #84
(Score: 0.461)
4. Dr. Matt Walker: How to Structure Your Sleep, Use Naps & Time Caffeine | Huberman Lab Guest Series
(Score: 0.455)

In [23]:
# run a hybrid query for articles about Art in the title vector and only include results with the phrase "Leonardo da Vinci" in the text
results = search_redis(openai_client,
                       redis_client,
                       "Sleep and Exercise",
                       vector_field="title_vector",
                       k=5,
                       hybrid_fields=create_hybrid_field("text", "Huberman")
                       )
# find specific mention of Leonardo da Vinci in the text that our full-text-search query returned
mention = [sentence for sentence in results[0].text.split("\n") if "Huberman" in sentence][0]
mention

0. Master Your Sleep & Be More Alert When Awake
(Score: 0.527)
1. Dr. Samer Hattar: Timing Light, Food, & Exercise for Better Sleep, Energy & Mood
(Score: 0.523)
2. How to Defeat Jet Lag, Shift Work & Sleeplessness
(Score: 0.518)
3. Dr. Matt Walker: Protocols to Improve Your Sleep | Huberman Lab Guest Series
(Score: 0.47)
4. Sleep Toolkit: Tools for Optimizing Sleep & Sleep-Wake Timing | Huberman Lab Podcast #84
(Score: 0.461)

'or check out the Huberman Lab Instagram'

In [24]:
results

[Document {'id': 'doc:2', 'payload': None, 'vector_score': '0.472522139549', 'title': 'Master Your Sleep & Be More Alert When Awake', 'text': "A note about sleepwalkers and\npeople with very vivid dreams,\ntheanine can often make\nyour dreams very vivid,\nsleepwalkers should be\ncareful about taking theanine,\neveryone should be careful\nabout taking anything,\nand don't take anything\nwithout consulting your\nboard-certified M.D.\nor healthcare professional first, okay?\nYour health is your responsibility,\nI am not gonna take responsibility\nfor what you decide to do\nexperimentally in any case,\nbut especially as it relates\nto supplementation and drugs.\nAs a important point, apigenin\nis a fairly potent estrogen inhibitor,\nso women who want to keep\ntheir estrogen levels high,\nor at whatever levels\nthey happen to be at,\nshould probably avoid apigenin altogether,\nand men, take that into\nconsideration as well,\nmen need estrogen also,\nyou don't wanna completely\neliminate your estrogen,\nthat it can create all\nsorts of bad effects\non libido and cognition, et cetera,\nso apigenin in some people\nis gonna be a pretty\nstrong estrogen inhibitor,\nso keep that in mind.\nThere are other things you can take\nto help you sleep better,\nthose are the legal ones\nthat, at least I'm aware of,\nhave pretty broad safety margins,\nbut again, you need to explore\nyour safety margins with any compound.\nI think a great website\nthat I can refer you to is examine.com,\nexamine, the word, just as it\nsounds, .com, is a website,\nI have no relation to them,\nbut there, you can find links\nto peer-reviewed studies\nfor any compound or supplement,\nas well as some important warnings\nrelated to the things I discussed,\nas well as any other thing\nthat you might decide to supplement with\nor ingest to help improve your sleep.\nOkay, that was a lot of information\nabout how to get better at sleeping,\nfalling asleep, wakefulness, et cetera.\nAn important feature of\nthis podcast, as you know,\nis that we dive deep into topics\nfor several episodes at a time,\nat least a month at a time,\nso by stopping here, I recognize\nthat there are probably\nmany more questions\nthat you still have,\nand the great thing about that\nis that we have another\nepisode coming up soon,\nI'm going to hold office hours\nwhere I'm going to answer\nyour specific questions\nabout episodes one and two,\nso if you have questions\nabout this episode,\nyou have questions about episode one,\nwrite them down, put them in the comments,\nI'll also do a post on Instagram\nwhere you can put them\nin the comments there,\nbut put them in the comments\nto this episode as well,\nplease recommend the\npodcast if you like it,\nplease subscribe to it here on YouTube,\nplease subscribe to it on Apple,\nwe're now on Spotify as well,\nrecommend it to a friend,\nthe community that we're creating here\naround these topics of\nsleep and wakefulness\nand other neuroscience-\nand health-related themes\nis best supported by your\ninvolvement and your questions,\nand so I'm going to be\nreading all of your questions,\ndistilling those into the\nmost commonly asked questions\nand liked questions,\nso if you see something below\nthat you are particularly interested in,\nyou don't have to put\nthat question in again,\nyou can just give it a like,\nthe little thumbs-up tab,\nand if you're listening to\nthis on Spotify or Apple,\nplease go to YouTube, subscribe,\nand put your question there,\nor check out the Huberman Lab Instagram\nand you can put your questions there\nso that next episode, I\ncan answer those questions\nand then we can move forward\neven more deeply into\nthese critical topics\naround sleep and wakefulness\nso that you can be armed\nwith all the information\nand resources that you need.\nLast but not least, a number of you\nhave very graciously asked how\nyou can support the podcast,\nthe best way to support the podcast\nis to subscribe on YouTube or\none of the other platforms,\nwe are now on Spotify and Apple,\nand the other way you can\nreally support the podcast\nis to check out our sponsors,\nwhich were discussed at the beginning.\nSo thank you so much for\nyour time and attention,\nand above all, thank you for\nyour interest in science.\n(energetic music)", 'chunk_key': 'nm1TxQj9IsQ_chunk_18'},
 Document {'id': 'doc:43', 'payload': None, 'vector_score': '0.476793467999', 'title': 'Dr. Samer Hattar: Timing Light, Food, & Exercise for Better Sleep, Energy & Mood', 'text': "does post from time to time,\nmostly pictures of food\nthat is incredibly spicy,\nbut also information about chronobiology.\nHe comes on for an\nInstagram Live every once\nin a while with me.\nSo, definitely give him a\nfollow there and on Twitter.\nAnd I'm sure that he'll be\nhappy to answer questions\nand entertain any and all\ndiscussions about chronobiology.\n- Absolutely, yeah.\nAnd light, yeah.\n- Great, thank you, Samer.\n- Awesome, thank you, Andrew.\n- Thank you for joining\nme for my conversation\nwith Dr. Samer Hattar.\nI hope you found it as interesting\nand informative as I did.\nIf you're enjoying this podcast\nand/or learning from it,\nplease subscribe to our YouTube channel.\nIn addition, please leave\nus comments and feedback\nin the comments section on YouTube.\nA great thing to do there\nwould be to make suggestions\nabout future topics you'd like us to cover\nor future guests you'd like me to host\non the Huberman Lab Podcast.\nIn addition, please\nsubscribe to our podcast\non Apple and Spotify.\nAnd on Apple, you can leave\nus up to a five star review.\nPlease also check out the\nsponsors that we mentioned\nat the beginning of the podcast.\nThat's a terrific way to support us.\nAnd we have a Patreon, it's\npatreon.com/andrewhuberman.\nAnd there you can support the podcast\nat any level that you like.\nFor those of you that are interested\nin supporting scientific research,\nyou can support the research\nin my laboratory on stress,\non sleep, and human performance\nand other related topics,\nby going to\nHubermanLab.stanford.edu/giving.\nAnd there you can make a\ntax deductible donation\nat any level that you like.\nIf you're not already\nfollowing us on Instagram,\nplease follow us @HubermanLab on Instagram\nand also on Twitter.\nBoth those places I teach neuroscience\nand offer information\nthat's not always covered\non the Huberman Lab Podcast.\nAnd last, but certainly not least,\nthank you for your interest in science.\n[light music]", 'chunk_key': 'oUu3f0ETMJQ_chunk_32'},
 Document {'id': 'doc:4', 'payload': None, 'vector_score': '0.481890261173', 'title': 'How to Defeat Jet Lag, Shift Work & Sleeplessness', 'text': "So up until now I've been reluctant\nto recommend specific supplement brands.\nThe supplement industry\nis kind of a wild west\nof different brands,\ndifferent levels of\nquality and stringency.\nIt can be very complicated\nand what's on the bottle is\nnot always what you're getting.\nThe quality of what you're getting\nvaries from company to company,\nand even from substance to\nsubstance, batch to batch.\nSo I'm pleased to say that\nI'm partnering with Thorne,\nThorne, spelled T-H-O-R-N-E,\nis a supplement company that\nworks with the Mayo Clinic,\nand with pretty much all the\nmajor sports team organizations\nand that I know to have the\nhighest levels of stringency\nin terms of what's in the bottle\nmatches what's listed on the bottle,\nand in terms of the quality\nof what they put in those supplements.\nSo, while I mentioned earlier,\nthat supplements aren't for everybody.\nIf you're interested in trying\nsome of these supplements\nyou might want to check out Thorne.\nIf you want to do that you can go to\nthorne.com/u/huberman.\nSo it's t-h-o-r-n-e.com,\nc-o-m slash the letter u slash huberman,\nand if you do that,\nthey'll give you 20% off\nany of the supplements\nthat you happen to purchase from Thorne.\nThanks so much for your\ntime and attention.\nI really appreciate it.\nSee you next time on the\nHuberman Lab Podcast.\nAnd as always, thanks for\nyour interest in science.\n[bright music]", 'chunk_key': 'NAATB55oxeQ_chunk_24'},
 Document {'id': 'doc:194', 'payload': None, 'vector_score': '0.529728889465', 'title': 'Dr. Matt Walker: Protocols to Improve Your Sleep | Huberman Lab Guest Series', 'text': "guests that you'd like me to feature on\nthe hubman Lab podcast please put those\nin the comment section on YouTube I do\nread all the comments on many episodes\nof The hubman Lab podcast we discuss\nsupplements while supplements aren't\nnecessary for everybody many people\nderive tremendous benefit from them for\nthings like improving sleep for hormone\nsupport and for Focus to learn more\nabout the supplements discussed on the\nhubman loud podcast go to live momentus\nspelled o us that's Liv mous.com\nhuberman if you're not already following\nme on social media I'm hubman lab on all\nsocial media platforms so that's\nInstagram X LinkedIn Facebook and\nthreads and on all those platforms I\ndiscuss science and science related\ntools some of which overlaps with the\ncontent of the hubman Lab podcast but\nmuch of which is distinct from the\ncontent covered on the huberman Lab\npodcast so again it's hubman lab on all\nsocial media platforms if you haven't\nalready subscribed to our neural network\nnewsletter our neural network newsletter\nis a zeroc cost newsletter that provides\npodcast summaries as well as protocols\nin the form of brief 1 to three page PD\nf s that cover everything from\nneuroplasticity and learning to sleep to\ndeliberate cold exposure and deliberate\nheat exposure we have a foundational\nFitness protocol and much more all of\nwhich again is completely zero cost you\nsimply go to huberman lab.com go to the\nmenu tab scroll down to newsletter and\nby supplying your email you can\nsubscribe I want to point out that we do\nnot share your email with anybody thank\nyou once again for joining me for\ntoday's discussion all about sleep with\nDr Matthew Walker and last but certainly\nnot least thank you for your interest in\nsign that's\n[Music]", 'chunk_key': 'hvPGfcAgk9Y_chunk_31'},
 Document {'id': 'doc:84', 'payload': None, 'vector_score': '0.538903474808', 'title': 'Sleep Toolkit: Tools for Optimizing Sleep & Sleep-Wake Timing | Huberman Lab Podcast #84', 'text': "necessary for everybody,\nmany people derive\ntremendous benefit from them\nfor things like sleep and focus\nand hormone support and so forth.\nFor reasons mentioned at the\nbeginning of the episode,\nwe are now partnered with\nMomentous supplements.\nIf you go to livemomentous.com/huberman,\nyou'll see many of the\nsupplements described on today's\nand other episodes of\nThe Huberman Lab Podcast.\nAgain, all as\nsingle-ingredient formulations.\nThey ship internationally,\ntheir quality is exceedingly high,\nand by largely focusing\non single ingredient\nand various dosages of\ndifferent supplements,\nyou can create the optimized\nsupplement protocol for you.\nIf you're not already\nfollowing us on social media,\nwe are @hubermanlab on Instagram\nand also @hubermanlab on Twitter.\nThere, I cover science\nand science-related tools,\nsome of which overlaps\nwith the content of The\nHuberman Lab Podcast,\nand other of which,\nI should say much of which,\nis distinct from the information\ncovered on this podcast.\nIf you're interested\nin obtaining protocols\nor summaries from these podcasts,\nyou can get those completely free of cost\nby going to hubermanlab.com.\nGo to the menu at hubermanlab.com.\nGo to the Neural Network Newsletter.\nYou simply provide us your email\nand you'll get the\nNeural Network Newsletter\nfor free each month.\nYou can also find previous newsletters\nthere at hubermanlab.com.\nFor instance, Toolkit for Sleep\nor Deliberate Cold Exposure\nand so on and so forth.\nAgain, we don't share\nyour email with anybody.\nSo our privacy policy is\nmade very clear there.\nAnd it's completely zero cost.\nSo thank you for joining\nme today for our discussion\nabout tools for optimizing sleep,\nand in doing so, tools for\noptimizing not just sleep,\nbut your daytime feelings\nof alertness and focus\nand your overall health.\nAnd last but certainly not least,\nthank you for your interest in science.\n[bright music]", 'chunk_key': 'h2aWYjSA1Jc_chunk_25'}]